apiVersion: v1
kind: Service
metadata:
  namespace: game-2048
  name: service-2048
spec:
  selector:
    app.kubernetes.io/name: app-2048
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80