apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-2048
  namespace: game-2048
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "game-2048-ip"
    networking.gke.io/managed-certificates: "game-ssl-cert"
    kubernetes.io/ingress.allow-http: "true"
spec:
  rules:
    - host: games-ai-gcp.ustpace.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: service-2048
                port:
                  number: 80